import { useState } from 'react'
import {
  Search, MessageSquare, Target, Calendar, CheckCircle, Phone, Send,
  Wrench, DollarSign, TrendingUp, Users, ChevronsRight,
} from 'lucide-react'
import { getTheme, ACCENTS } from './theme'
import { SheetShell, LogoMark, Eyebrow, GradientText, Callout, MobileSection, useIsMobile } from './ui'

const JOURNEY = [
  { label: 'Discover', icon: Search, color: ACCENTS.indigo },
  { label: 'Engage', icon: MessageSquare, color: ACCENTS.indigo },
  { label: 'Qualify', icon: Target, color: ACCENTS.violet },
  { label: 'Schedule', icon: Calendar, color: ACCENTS.violet },
  { label: 'Book', icon: CheckCircle, color: ACCENTS.violet },
  { label: 'Confirm', icon: Phone, color: ACCENTS.pink },
  { label: 'Communicate', icon: Send, color: ACCENTS.pink },
  { label: 'Deliver', icon: Wrench, color: ACCENTS.amber },
  { label: 'Invoice', icon: DollarSign, color: ACCENTS.emerald },
  { label: 'Attribute', icon: TrendingUp, color: ACCENTS.emerald },
]

const LAYERS = [
  {
    color: ACCENTS.indigo, title: 'Assist', sub: 'Customer Intent + Conversion',
    items: ['Capture', 'Qualification', 'Availability', 'Booking', 'Attribution'],
  },
  {
    color: ACCENTS.violet, title: 'Connect', sub: 'Customer Communication',
    items: ['Calling', 'Messaging', 'Email', 'AI (Adam & Ava)', 'Conversation history', 'Customer context'],
  },
  {
    color: ACCENTS.emerald, title: 'Job Management Platform', sub: 'Operational Execution',
    items: ['Customers', 'Quotes', 'Jobs', 'Scheduling', 'Technicians', 'Invoices'],
  },
]

function AssistConnectA4({ t }) {
  return (
    <div style={{ height: '100%', boxSizing: 'border-box', padding: '8mm 12mm', display: 'flex', flexDirection: 'column', gap: '3.5mm' }}>

      {/* Header */}
      <div style={{ height: '11mm', flex: '0 0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <LogoMark t={t} />
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Eyebrow t={t} color={ACCENTS.violet}>Assist + Connect</Eyebrow>
          <span style={{ fontSize: 10, color: t.muted, fontWeight: 600 }}>Partner Product Sheet</span>
        </div>
      </div>

      {/* Hero */}
      <div style={{ flex: '0 0 auto', display: 'flex', flexDirection: 'column', gap: 4 }}>
        <h1 style={{ margin: 0, fontSize: 25, fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1.12, color: t.heading, maxWidth: '86%' }}>
          Your job management system manages the job.{' '}
          <GradientText t={t}>Autofront manages the journey.</GradientText>
        </h1>
        <p style={{ margin: 0, fontSize: 10.5, lineHeight: 1.5, color: t.body, maxWidth: '80%' }}>
          The customer relationship starts before a job exists and continues after the booking. Assist + Connect
          joins that journey to the operational systems already running the business.
        </p>
      </div>

      {/* Journey diagram */}
      <div style={{ flex: '0 0 auto', display: 'flex', flexDirection: 'column', gap: 5, padding: '5mm 0' }}>
        <div style={{ fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: t.muted }}>From first click or call to the revenue generated by the completed job</div>
        <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'nowrap', gap: 4, justifyContent: 'space-between' }}>
          {JOURNEY.map((s, i) => (
            <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: 4, flex: i === JOURNEY.length - 1 ? '0 0 auto' : '1 1 auto' }}>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 3, flex: '0 0 auto' }}>
                <div style={{ width: 24, height: 24, borderRadius: '50%', background: t.tint(s.color, t.mode === 'dark' ? '22' : '12'), border: `1px solid ${t.tintBorder(s.color)}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <s.icon size={12} color={s.color} />
                </div>
                <span style={{ fontSize: 7.6, fontWeight: 700, color: t.heading, whiteSpace: 'nowrap' }}>{s.label}</span>
              </div>
              {i < JOURNEY.length - 1 && <div style={{ flex: '1 1 auto', height: 1, background: t.border, minWidth: 4 }} />}
            </div>
          ))}
        </div>
      </div>

      {/* Three layers */}
      <div style={{ height: '48mm', flex: '0 0 auto', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gridTemplateRows: '1fr', gap: '4mm' }}>
        {LAYERS.map((l, i) => (
          <div key={l.title} style={{
            background: t.mode === 'dark' ? 'rgba(255,255,255,0.035)' : '#ffffff',
            border: `1px solid ${t.tintBorder(l.color)}`, borderRadius: 14, padding: '10px 12px',
            display: 'flex', flexDirection: 'column', gap: 6,
            boxShadow: t.mode === 'light' ? t.cardShadow : 'none', position: 'relative',
          }}>
            <div>
              <div style={{ fontSize: 13, fontWeight: 800, color: l.color, letterSpacing: '-0.01em' }}>{l.title}</div>
              <div style={{ fontSize: 8.5, color: t.muted, fontWeight: 600 }}>{l.sub}</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 3, marginTop: 2 }}>
              {l.items.map(it => (
                <div key={it} style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 9, color: t.body }}>
                  <span style={{ width: 4, height: 4, borderRadius: '50%', background: l.color, flex: '0 0 auto' }} />
                  {it}
                </div>
              ))}
            </div>
            {i < LAYERS.length - 1 && (
              <ChevronsRight size={14} color={t.faint} style={{ position: 'absolute', right: -10, top: '50%', transform: 'translateY(-50%)', zIndex: 1 }} />
            )}
          </div>
        ))}
      </div>

      {/* Partner positioning */}
      <div style={{ flex: '0 0 auto', display: 'flex', alignItems: 'center', gap: '10mm', padding: '3mm 0' }}>
        <div style={{ flex: '1 1 60%' }}>
          <div style={{ fontSize: 13.5, fontWeight: 800, color: t.heading, letterSpacing: '-0.01em', marginBottom: 4 }}>Extend the systems your customers already use.</div>
          <p style={{ margin: 0, fontSize: 9.5, lineHeight: 1.5, color: t.body }}>
            Job management systems are excellent at managing operational work once it exists. Autofront adds the
            customer engagement and orchestration layer around that work — for the platform, and for the partner
            who implements and supports it.
          </p>
        </div>
        <div style={{ flex: '0 0 auto', display: 'flex', alignItems: 'center', gap: 6 }}>
          {['Customer', 'Autofront', 'Job Management', 'Business Operations'].map((label, i, arr) => (
            <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <div style={{
                padding: '6px 10px', borderRadius: 10, fontSize: 8.5, fontWeight: 700, whiteSpace: 'nowrap',
                background: i === 1 ? t.tint(ACCENTS.violet, t.mode === 'dark' ? '22' : '14') : t.panelAlt,
                border: `1px solid ${i === 1 ? t.tintBorder(ACCENTS.violet) : t.border}`,
                color: i === 1 ? (t.mode === 'dark' ? '#c4b5fd' : '#7c3aed') : t.heading,
              }}>{label}</div>
              {i < arr.length - 1 && <ChevronsRight size={12} color={t.faint} />}
            </div>
          ))}
        </div>
      </div>

      {/* Closing */}
      <div style={{ flex: '1 1 auto', display: 'flex', alignItems: 'center', gap: '8mm' }}>
        <Callout t={t} color={ACCENTS.violet} style={{ flex: '1 1 auto', height: '100%' }}>
          Capture. Qualify. Book. Communicate. Convert.
        </Callout>
        <div style={{ flex: '0 0 auto', maxWidth: '68mm', fontSize: 9, lineHeight: 1.5, color: t.muted, display: 'flex', alignItems: 'center', gap: 6 }}>
          <Users size={14} color={t.mode === 'dark' ? '#8b5cf6' : '#7c3aed'} style={{ flex: '0 0 auto' }} />
          Ask your Autofront contact about introducing Assist + Connect to customers who need more from their existing platform.
        </div>
      </div>

    </div>
  )
}

function AssistConnectMobile({ t }) {
  return (
    <div style={{ boxSizing: 'border-box', padding: '26px 20px 34px', display: 'flex', flexDirection: 'column', gap: 28 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <LogoMark t={t} size={24} />
        <Eyebrow t={t} color={ACCENTS.violet}>Assist + Connect</Eyebrow>
      </div>

      <div>
        <h1 style={{ margin: '0 0 8px', fontSize: 23, fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1.18, color: t.heading }}>
          Your job management system manages the job.{' '}
          <GradientText t={t}>Autofront manages the journey.</GradientText>
        </h1>
        <p style={{ margin: 0, fontSize: 14, lineHeight: 1.6, color: t.body }}>
          The customer relationship starts before a job exists and continues after the booking. Assist + Connect
          joins that journey to the operational systems already running the business.
        </p>
      </div>

      <MobileSection t={t} label="From first click or call to revenue" />
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {JOURNEY.map(s => (
            <div key={s.label} style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: t.tint(s.color, t.mode === 'dark' ? '16' : '0e'),
              border: `1px solid ${t.tintBorder(s.color)}`,
              borderRadius: 99, padding: '6px 11px',
            }}>
              <s.icon size={14} color={s.color} />
              <span style={{ fontSize: 11, fontWeight: 700, color: t.heading, whiteSpace: 'nowrap' }}>{s.label}</span>
            </div>
          ))}
      </div>

      <MobileSection t={t} label="The three layers" />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
        {LAYERS.map(l => (
          <div key={l.title} style={{
            background: t.mode === 'dark' ? 'rgba(255,255,255,0.035)' : '#ffffff',
            border: `1px solid ${t.tintBorder(l.color)}`, borderRadius: 14, padding: '14px 16px',
            display: 'flex', flexDirection: 'column', gap: 8,
            boxShadow: t.mode === 'light' ? t.cardShadow : 'none',
          }}>
            <div>
              <div style={{ fontSize: 16, fontWeight: 800, color: l.color, letterSpacing: '-0.01em' }}>{l.title}</div>
              <div style={{ fontSize: 11, color: t.muted, fontWeight: 600 }}>{l.sub}</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
              {l.items.map(it => (
                <div key={it} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: t.body }}>
                  <span style={{ width: 5, height: 5, borderRadius: '50%', background: l.color, flex: '0 0 auto' }} />
                  {it}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <MobileSection t={t} label="Partner positioning" />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div style={{ fontSize: 17, fontWeight: 800, color: t.heading, letterSpacing: '-0.01em' }}>Extend the systems your customers already use.</div>
        <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.6, color: t.body }}>
          Job management systems are excellent at managing operational work once it exists. Autofront adds the
          customer engagement and orchestration layer around that work — for the platform, and for the partner
          who implements and supports it.
        </p>
        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 6 }}>
          {['Customer', 'Autofront', 'Job Management', 'Business Operations'].map((label, i, arr) => (
            <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <div style={{
                padding: '6px 10px', borderRadius: 10, fontSize: 11.5, fontWeight: 700, whiteSpace: 'nowrap',
                background: i === 1 ? t.tint(ACCENTS.violet, t.mode === 'dark' ? '22' : '14') : t.panelAlt,
                border: `1px solid ${i === 1 ? t.tintBorder(ACCENTS.violet) : t.border}`,
                color: i === 1 ? (t.mode === 'dark' ? '#c4b5fd' : '#7c3aed') : t.heading,
              }}>{label}</div>
              {i < arr.length - 1 && <ChevronsRight size={13} color={t.faint} />}
            </div>
          ))}
        </div>
      </div>

      <MobileSection t={t} />
      <Callout t={t} color={ACCENTS.violet}>Capture. Qualify. Book. Communicate. Convert.</Callout>
      <div style={{ fontSize: 13, lineHeight: 1.55, color: t.muted, display: 'flex', gap: 8 }}>
        <Users size={16} color={t.mode === 'dark' ? '#8b5cf6' : '#7c3aed'} style={{ flex: '0 0 auto', marginTop: 2 }} />
        Ask your Autofront contact about introducing Assist + Connect to customers who need more from their existing platform.
      </div>
    </div>
  )
}

export default function AssistConnectSheet() {
  const [theme, setTheme] = useState('dark')
  const mobile = useIsMobile()
  const t = getTheme(theme, mobile)
  return (
    <SheetShell t={t} theme={theme} setTheme={setTheme} title="Assist + Connect">
      {mobile ? <AssistConnectMobile t={t} /> : <AssistConnectA4 t={t} />}
    </SheetShell>
  )
}
